# Generated by Django 3.1.3 on 2020-11-26 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_remove_project_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'project')},
        ),
        migrations.AlterIndexTogether(
            name='rate',
            index_together={('user', 'project')},
        ),
    ]
